### ISSUE TITLE
Remove header or adjust positions

### ISSUE THREAD

**Issue by rspurves** [jwoLondon/mobv#1]
@jwoLondon On my monitor/ set up the header centres the heatmap/ map which then results in then not being visible, with lots of unnecessary padding to the left. Could we remove the header/ left align the heatmap? I guess that means messing with the css, but I honestly don't know where to start...

**Comment by jwoLondon** [comment]
Just to be clear, are you wanting everything aligned left, as indicated by the arrows? Or just the visualizations?

![alignLeft](https://user-images.githubusercontent.com/1846999/80634033-ad23a580-8a51-11ea-82a3-bc9fb2e555d9.jpg)

**Comment by rspurves** [comment]
So on my monitor it looks like this:

![image](https://user-images.githubusercontent.com/3155166/80634392-b6654000-8a5a-11ea-9b1e-8552b03dcd42.png)

The monitor is wide enough to show the whole vis with no scrolling, which is much nicer. So it would be good to be able to do this. Turning off the header fixes it...

**Comment by jwoLondon** [comment]
Fixed this now. If you include the `wide` class for the enclosing `<div>` (which I have done for the Zurich example), it will centre the vis in the available space. Layout can be a little ugly, but functional. The alternative of removing the fixed width of the main body of the page would be worse though as text would be uncomfortably wide.

<img width="1435" alt="centredWide" src="https://user-images.githubusercontent.com/1846999/80640576-80748b80-8a5b-11ea-8541-bf12d6c4689d.png">

**Comment by rspurves** [comment]
Great, that is much better. Thanks
