### ISSUE TITLE
Cleaning New York data

### ISSUE THREAD

**Issue by jwoLondon** [jwoLondon/mobv#2]
The New York bicycle data include the following station:

```104055175,Manhattan Bridge Interference Calibration 2019 Bike Counter OUT```

This is currently not listed in the `stationLocations-Bicycle.csv` and as a result it has a label of _null_ in the two timeline visualizations. While the name suggests this may not be a meaningful station, it does appear to generate a coherent signal. We need either to remove it from the data or add its name and location to the stationLocations file.

Should we also remove the three Broadway at 50th St stations as these stopped generating data by the 22nd January. It would also help to declutter the line chart.

**Comment by rspurves** [comment]
I cleaned up the stations a bit, and also "moved" Staten Island to allow me to generate a more or less tidy map. I didn't realise the calibration station was in the data, it was probably one of the null island ones, so I would take it out. @rastrau wanted to merge some stations in/outs but I am not sure how easy that will be...

**Comment by jwoLondon** [comment]
I've updated the specs so that any unmatched data (i.e. absent in the stationLocation file) are removed when visualised. This should stop us from filtering out the unused data at source though, but I'll leave that to Ralph in case he wants to merge any of the other stations.

**Comment by rastrau** [comment]
I'm working on creating the `StationLocations.csv` using the R script, too. I'll have to think about merging directions, but if I go ahead with that, I would do it the same way as in Zurich (i.e. in all data files, counts, reference, and locations), thus there would be no need to change anything on the frontend.

I think I misunderstood some of the workings of the heatmap: I thought the rows were populated based on `station_id`s (with a look-up of `station_name`), but now I think it is based on `station_name` directly. Thus, we currently have one heatmap record `Southbound` but three locations in the map with that name (some counters have unfortunate names in New York). If my understanding is correct, would it be hard to change that in the frontend, @jwoLondon? I think if we base "what makes a record in the heatmap" on `station_id` we are more compliant with the data specification where we require uniqueness only for `station_id`, not for `station_name`.

**Comment by jwoLondon** [comment]
I think your original assumption was correct. We use the station id, not the name as the key to link the two tables.

For the record, this is my assumption of the data specifications and the relations:

* There is a station location file (any name) must include the following fields (can be in any order and any additional fields are currently ignored)

  ```station_id,station_name,lat,lon```

  Each `station_id` should be unique but names need not be (nor locations, although that can produce a cluttered map)

* There is a reference file (any name) containing the the following fields (in any order and additional fields ignored)

  ```id,value```

  Each `id` value should uniquely identify a combined station and temporal period and each `value` is some benchmark count value (e.g. median)

* There is a time series file (any name) with the following fields (in any order and additional fields ignored):

  ```date,station,id,count```

   Where `station` should match one of the values in the `station_id` field of the station location file. The `id` field must contain values that match one of the `id` in the reference file. `date` and `count` are the actual data.
